### PR TITLE
feat: Add support for single independ jar

### PR DESCRIPTION
**Pull request by wgzhao**
execute `mvn clean package` , then you can simplely run `java -jar distribution/target/distribution-<version>-jar-with-dependencies.jar`

Signed-off-by: wgzhao <wgzhao@gmail.com>

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
I ever thought of packaging a shaded jar (fat jar).

Currently, we can run the application by `bin/dryad` already, and the script help to load the classpath. With this patch, the situation doesn't change from my perspective since we should continue to pass the jar balls and if we'd like to load dynamic dependencies such as log configuration or SPI implementation, we need to configure the classpath again.

Although, it can be how Java is designed to use. Let me think a little bit.

**Comment by wgzhao** [comment]
maybe you can try [sprint shell](https://spring.io/projects/spring-shell) ?

**Comment by tisonkun** [comment]
@wgzhao is it possible to use Spring Shell without introducing other Spring dependencies (Spring Boot, starters, framework)?

Also What I'm going to do here is packaging a CLI, instead of implementing a shell.

**Comment by wgzhao** [comment]
> @wgzhao is it possible to use Spring Shell without introducing other Spring dependencies (Spring Boot, starters, framework)?
> 
> Also What I'm going to do here is packaging a CLI, instead of implementing a shell.

It needs spring-boot-starter, other dependencies are optional

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your contribution and explanation @wgzhao!

Although, I don't want to add dep to spring, and bundling a fat jar seems not a better solution than the current solution for me.

Closed as won't do in this direction. Thanks for your idea :)

**Pull request closed without merging**
